import type { NextPage } from "next";
import Head from "next/head";
import { Button, message } from "antd";
import { Auth } from "../../services/auth";
import { Form, Input, Checkbox, FormikDebug, SubmitButton } from "formik-antd";
import { Formik } from "formik";
import sha256 from "crypto-js/sha256";

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Formik
        initialValues={{ username: "", password: "" }}
        onSubmit={async (values, actions) => {
          try {
            const hashPassword = sha256(values.password).toString();
            const data = { ...values, password: hashPassword };
            const req = await Auth.signIn(data);
            console.log(req.data);
          } catch (error: any) {
            console.error(error);
            alert(error?.message);
          }
          // message.info(JSON.stringify(values, null, 4));
          // actions.setSubmitting(false);
          // actions.resetForm();
        }}
        render={() => (
          <Form>
            <Input name="username" placeholder="First Name" />
            <Input.Password name="password" placeholder="Password" />
            {/* <Checkbox name="newsletter">Newsletter</Checkbox> */}
            {/* <FormikDebug /> */}
            <SubmitButton>Submit</SubmitButton>
          </Form>
        )}
      />
    </>
  );
};

export default Login;
